### ISSUE TITLE
Support plugins

### ISSUE THREAD

**Issue by pschichtel** [cubyte-oss/puppet-bareos#1]

**Comment by wagnst** [comment]
- [MySql general](http://doc.bareos.org/master/html/bareos-manual-main-reference.html#x1-507000H.2.3)
- [runscript](http://doc.bareos.org/master/html/bareos-manual-main-reference.html#x1-509000H.2.3)
- [bpipe](http://doc.bareos.org/master/html/bareos-manual-main-reference.html#x1-510000H.2.3)

**Comment by pschichtel** [comment]
@wagnst this is about plugin support, not about backing up mysql
