### ISSUE TITLE
Allow setting fd process priority/niceness

### ISSUE THREAD

**Issue by pschichtel** [cubyte-oss/puppet-bareos#5]
generite /etc/defaults/bareos-fs and override $DAEMON with a call to nice

**Comment by pschichtel** [comment]
Additionally: provide a `/etc/systemd/system/bareos-filedaemon.service.d/nice.conf` with this content:

```
[Service]
Nice=10
```

**Comment by wagnst** [comment]
what if we would limit it with cpulimit
e.g.

```
cpulimit -e bareos-fd -l 30
```

see: [HowToForge](https://www.howtoforge.com/how-to-limit-cpu-usage-of-a-process-with-cpulimit-debian-ubuntu)

**Comment by pschichtel** [comment]
CPU limit is an additional tool, nice is included and also has systemd support. However this will be done generic enough to allow other configurations

**Comment by pschichtel** [comment]
will not be implemented by this module as its too specific, however enough information is provided by the module to easily implement it in a separate module
